### ISSUE TITLE
`Json < InfoSetupProvider < '_ > >` data guard failed: Parse("https://myship.tld", Error("expected value", line: 1, column: 1)).

### ISSUE THREAD

**Issue by morelazers** [aquarial/urbit-lfs-filehosting#2]
**Edit** Pretty sure it's local to my setup, the app works fine when using the makefile to setup on a fakezod.

I've set up my ship with HTTPS via nginx and letsencrypt, and have added the fileserver as a separate nginx site, pointing to a subdomain.

I'm following [these instructions](https://github.com/aquarial/urbit-lfs-filehosting/blob/master/data/provider.md), but when I try to connect to the fileserver from my dojo with the (personalised) command:

`:lfs-provider &lfs-provider-command [threadid=~ %connect-server loopback="https://your-ship.domain.tld" fileserver="https://fileserver.domain.tdl" token="THE_TOKEN_FROM_EARLIER"]`

I receive a 400 error in the dojo, which prints out the _second_ URL (for the fileserver).

When I view the Rust server logs, I see the error from the issue title, which seems to be complaining about the _first_ URL (the one for the ship). I presume this is the more trustworthy error message.

Not sure how to proceed.

Note: I am not running the ship on a subdomain. I originally tried to do that when setting up the LFS-fileserver, but since I have previously [requested an SSL certificate directly from my dojo](https://urbit.org/using/os/basics#configuring-ssl), the certificates did not match when browsing through the subdomain.

Will give local debugging a crack in the next few days, I'm a Rust novice but maybe I can smoke out the problem.

**Comment by aquarial** [comment]
My b: I pushed a change to JSON handling for the rust code and hoon code, but forgot to update the ~tabnus provider code. So installing from source works well, but `|install`ing won't work yet.

**Comment by aquarial** [comment]
Pushed `+vats` hash `0v14.26pno.2fi97.f6cuk.1kgu9.hm5jb.o9dvt.5dkef.l5h5g.i142i.nv699` to the `~nilsud` tabnus moon. Should work with the up-to-date rust code.

**Comment by morelazers** [comment]
It works! Thanks for the rapid response.
